### ISSUE TITLE
Links rotos Material de apoyo

### ISSUE THREAD

**Issue by edisonbermudez** [alejo8591/unipiloto-apm-5#10]
https://github.com/alejo8591/unipiloto-apm-5/wiki/Material-de-Apoyo

Git:
	- 	Git Immersion en Español; comandos y características de este sistema de control de versiones
	http://bit.ly/1FSulER
	- 	Git From The Bottom Up
	http://ftp.newartisans.com/pub/git.from.bottom.up.pdf
JavaScript: Guias de Estilo
	-	Google JavaScript Style Guide
MOOCs
	-	NPTEL
Node.JS
	Libros o E-books, Artículos de Interes	
		-	JavaScript and Node Fundamentals
Regular Expressions
	-	Regular Expression: Match Unicode Block Range

**Comment by alejo8591** [comment]
@camuskool agradezco la información, ya fueron reparados los links, e incluso se agregan dos secciones.
