### ISSUE TITLE
ayuda con el git

### ISSUE THREAD

**Issue by owenkmus** [alejo8591/unipiloto-apm-5#12]
Profe que pena molestarlo, pero he tratado de subir algunos cambios, y me sale este error

git add .
git commit -m "validador login"
// hasta aca lo hace bien, pero cuando hago esto..
git push origin christian

me salen estos errores

error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/danapamela/product-app'

solo me dejo hacer git push origin master...a mi rama no me deja.....

le dejo mi numero por si me pueden colaborar 3008101803

**Comment by alejo8591** [comment]
@owenkmus cuéntame como creaste la rama?, en el momento que vas a hacer el commit y luego el push en que rama lo haces?, listame las ramas creadas (comando: git branch)?

**Comment by owenkmus** [comment]
la rama la cree asi:

git checkout -b christian

y realizando el git branch me aparecen asi:

*christian
master

**Comment by alejo8591** [comment]
perfecto en la rama `christian` dile lo siguiente:

`git add -A`
`git commit -am "Mensaje"`
`git push origin christian`

Tal cual por favor...!!

**Comment by owenkmus** [comment]
Listo profe muchas gracias ya lo pude subir... casi que no!!!

**Comment by alejo8591** [comment]
@owenkmus te sirvieron los comandos?

**Comment by owenkmus** [comment]
Si profe me sirvieron todos..... aunq no se por q  no sirvieron los q estaba utilizando, si eos fueron los q utilice en clase

**Comment by alejo8591** [comment]
- @owenkmus porque el `git add .` es para pasar a `stage` en el directorio presente, en cambio con `git add -A` pasa a `stage` todas las novedades del repo sin importar donde este ubicado dentro del repo.
- En el caso del commit cuando le dices `git commit -m "mensaje"` solo envías el mensaje pero no haces commit del repositorio como tal. Con `git commit -am "mensaje"` si pasas todo lo que esta en `stage` al repo.

**Comment by owenkmus** [comment]
Ok... muchas gracias!!
