### ISSUE TITLE
Error al probar Aplicacion acabada de crear

### ISSUE THREAD

**Issue by molinje** [alejo8591/unipiloto-apm-5#13]
Buenas noches...

a penas creo un proyecto esta saliendo el siguiente archivo adicional (README), seguí las instrucciones pero aun me da el error a continuación... este error sale a penas trato de ejecutar la aplicación después de creada:

Los nuevos proyectos se crean con un archivo README con el siguiente texto:

"
Ionic 2 App Base
=====================

This is the base template for Ionic 2 starter apps.

## Using this project

You'll need the Ionic CLI with support for v2 apps:

```bash
$ npm install -g ionic
```

Then run:

```bash
$ ionic start myApp
```

More info on this can be found on the Ionic [Getting Started](http://ionicframework.com/docs/v2/getting-started/) page.
"

ERROR:
C:\Users\John\Documents\GitHub\prueba-apm5\Module VIII\myApp>ionic serve

> ionic-app-base@ ionic:serve C:\Users\John\Documents\GitHub\prueba-apm5\Module
VIII\myApp
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livere
load-port" "35729"

keywords if/then/else require v5 option
module.js:327
    throw err;
    ^

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\John\Documents\GitHub\prueba-apm5\Module VII
I\myApp\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address"
"0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-app-base@ ionic:serve: `ionic-app-scripts serve "--v2" "--address
" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-app-base@ ionic:serve script 'ionic-app-scripts ser
ve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
npm ERR! This is most likely a problem with the ionic-app-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100
" "--livereload-port" "35729"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-app-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ionic-app-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\John\Documents\GitHub\prueba-apm5\Module VIII\myApp\npm-de
bug.log
There was an error serving your Ionic application: There was an error with the s
pawned command: serve

**Comment by alejo8591** [comment]
@molinje que versión de node tienes?, con la última actualización de ionic debes tener mínimo la `6.9.4`

**Comment by molinje** [comment]
Buenas noches, el dia de hoy volvi a correr el comando npm install para instalar dependencias y ya se soluciono el error.

Saludos y Gracias
