### ISSUE TITLE
Aplicaciones móviles para repaso y otras 

### ISSUE THREAD

**Issue by ingleo** [alejo8591/unipiloto-apm-5#2]
Compañeros les comparto las siguientes aplicaciones para repasar conceptos y otras:

HTML
https://play.google.com/store/apps/details?id=com.sololearn.htmltrial&hl=es

CSS
https://play.google.com/store/apps/details?id=com.sololearn.csstrial&hl=es

JS
https://play.google.com/store/apps/details?id=com.sololearn.javascript&hl=es

CLIENTE GITHUB 
https://play.google.com/store/apps/details?id=jp.forkhub&hl=es

MEJORAR SKILLS DE PROGRAMACIÓN
https://play.google.com/store/apps/details?id=com.enki.insights&hl=es

Saludos!

**Comment by alejo8591** [comment]
Se da cierre pues se agrega a [Material de Apoyo](https://github.com/alejo8591/unipiloto-apm-5/wiki/Material-de-Apoyo)
