### ISSUE TITLE
Sublime

### ISSUE THREAD

**Issue by elrichi2001** [alejo8591/unipiloto-apm-5#3]
Hola Profe

Estoy utilizando Sublime, pero este no me reconoce TypeScript. Me puede por favor recordar los pasos para instalar el package control?

Saludos y gracias!!

**Comment by alejo8591** [comment]
@elrichi2001 por favor dame más información, indicame la versión de Sublime, muestrame imagenes del `Package control instalado`, y si aparece algún error.

**Comment by elrichi2001** [comment]
Alejandro, muchas gracias, ya lo pude resolver.
https://packagecontrol.io/installation
