### ISSUE TITLE
Ionic serve –lab don’t work in RC2

### ISSUE THREAD

**Issue by alejo8591** [alejo8591/unipiloto-apm-5#7]
https://forum.ionicframework.com/t/ionic-serve-lab-dont-work-in-rc2/69862

**Comment by edisonbermudez** [comment]
Referencia: 
https://github.com/driftyco/ionic-app-scripts

Es necesario modificar el `package.json` en la parte de "scripts" debe aparecer así:

``` javascript
  "scripts": {
    "build": "ionic-app-scripts build",
    "serve": "ionic-app-scripts serve",
    "watch": "ionic-app-scripts watch"    
  }
```

En vez de:

``` javascript
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
  }
```

**Comment by alejo8591** [comment]
Por favor hacer pruebas con estas lineas en el `package.json`

``` javascript
  "scripts": {
    "build": "ionic-app-scripts build",
    "serve": "ionic-app-scripts serve",
    "watch": "ionic-app-scripts watch",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  }
```

**Comment by alejo8591** [comment]
Al parecer el problema ya fue solucionado por favor actualizar con:

`npm install -g cordova ionic`

> Por favor no se afanen si no tienen la misma versión, debe ser igual o superior

![captura de pantalla 2016-11-18 a las 2 47 49 p m](https://cloud.githubusercontent.com/assets/1151850/20444177/06541566-ad9e-11e6-9571-6e7e0370343b.png)

> Revisar la versión del paquete `ionic-app-scripts` tanto en la consola como en el `package.json`

![captura de pantalla 2016-11-18 a las 2 38 51 p m](https://cloud.githubusercontent.com/assets/1151850/20444229/33eba4bc-ad9e-11e6-86d8-b80cdbedcacb.png)
